# Generated by Django 3.2.3 on 2021-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('current_role', models.CharField(choices=[('ST', 'Student'), ('PT', 'Part Time'), ('FT', 'Full TIme'), ('OT', 'Others')], max_length=2)),
                ('recommedation', models.CharField(choices=[('DF', 'Definitely'), ('MB', 'Maybe'), ('NS', 'Not Sure')], max_length=2)),
                ('fav_language', models.CharField(choices=[('CP', 'C++'), ('JV', 'Java'), ('PY', 'Python')], max_length=2)),
                ('improvement', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('DV', 'Data Vizualisation')], max_length=2)),
            ],
        ),
    ]
